//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoedaCotacaoClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DePara
    {
        public string ID_MOEDA { get; set; }
        public int COD_COTACAO { get; set; }
        public DateTime DATA_REF { get; set; }
        public decimal VL_COTACAO { get; set; }
    }
}
