/*REPOSTA 1*/

SELECT  COUNT(P.IDSTATUS) AS QUANTIDADE_PROCESSOS, S.DSSTATUS AS DESCRICAO_STATUS 
FROM TB_PROCESSO P 
INNER JOIN TB_STATUS S ON 
P.IDSTATUS = S.IDSTATUS
GROUP BY P.IDSTATUS, S.DSSTATUS 


/*REPOSTA 2*/

SELECT P.NROPROCESSO AS NUMERO_PROCESSO, MAX(A.DTANDAMENTO) AS MAIOR_DATA_ANDAMENTO 
FROM TB_ANDAMENTO A 
INNER JOIN TB_PROCESSO P ON
A.IDPROCESSO = P.IDPROCESSO
WHERE YEAR(P.DTENCERRAMENTO) = 2013
GROUP BY P.NROPROCESSO, A.DTANDAMENTO


/*REPOSTA 3*/

SELECT COUNT(P.DTENCERRAMENTO) AS QUANTIDADE_ENCERRAMENTO
FROM TB_PROCESSO P
GROUP BY P.DTENCERRAMENTO
HAVING COUNT(P.DTENCERRAMENTO) > 5


/*REPOSTA 4*/

SELECT REPLICATE('0', 12 - LEN(NROPROCESSO)) + RTRIM(NROPROCESSO) AS NUMERO_PROCESSO FROM TB_PROCESSO
